language: ruby
rvm:
  - 1.9.3
  - 2.1.5
  - 2.3.1
gemfile:
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_edge.gemfile
matrix:
  exclude:
    - rvm: 2.3.1
      gemfile: gemfiles/activerecord_3.0.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/activerecord_3.1.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/activerecord_3.2.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/activerecord_3.0.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/activerecord_edge.gemfile
  allow_failures:
    - gemfile: gemfiles/activerecord_edge.gemfile
bundler_args: --without development
before_install:
  - gem install bundler
